# Generated by Django 4.2.9 on 2024-02-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0003_alter_customuser_test_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='', max_length=32),
            preserve_default=False,
        ),
    ]
