# Generated by Django 4.2.9 on 2024-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0004_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('uzbek', 'uzbek'), ('russian', 'russian')], max_length=32),
        ),
    ]
