# Generated by Django 4.2.9 on 2024-02-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0005_alter_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('Uzbekistan', 'Uzbekistan'), ('Qozogiston', 'Qozogiston'), ('Qirgiziston', 'Qirgiziston'), ('Tojikiston', 'Tojikiston'), ('Rossiya', 'Rossiya'), ('America', 'America'), ('Arab Amirligi', 'Arab Amirligi'), ('Boshqa davlat', 'Boshqa davlat')], max_length=32),
        ),
    ]
