# Generated by Django 4.2.9 on 2024-03-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0007_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('uzbek', 'uzbek'), ('russian', 'russian')], default='uzbek', max_length=32),
        ),
    ]
