# Generated by Django 4.2.9 on 2024-01-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskusers',
            name='test_access',
            field=models.BooleanField(default=False),
        ),
    ]
