# Generated by Django 4.2.9 on 2024-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_taskusers_test_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskusers',
            name='test_access',
            field=models.IntegerField(choices=[(1, 'no_access'), (2, 'first_second'), (3, 'third'), (4, 'all')], default=1),
        ),
    ]
