# Generated by Django 4.2.9 on 2024-01-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_taskusers_test_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskusers',
            name='test_access',
        ),
    ]
