# Generated by Django 4.2.9 on 2024-02-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_taskusers_test_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('1-2-Modul', '1-2-Modul'), ('3-Modul', '3-Modul')], max_length=150),
        ),
    ]
