# Generated by Django 4.2.9 on 2024-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='timer',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
