# Generated by Django 4.2.9 on 2024-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_task_options_task_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['global_order']},
        ),
        migrations.AddField(
            model_name='task',
            name='global_order',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
