# Generated by Django 4.2.9 on 2024-05-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_task_options_remove_task_global_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskusers',
            name='checking',
            field=models.BooleanField(blank=True, default=True, editable=False, null=True),
        ),
    ]
