# Generated by Django 4.2.9 on 2024-05-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_taskusers_checking'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskusers',
            name='all',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
