# Generated by Django 4.2.9 on 2024-05-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_taskusers_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskusers',
            name='all',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskusers',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
    ]
