# Generated by Django 4.2.9 on 2024-05-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_taskusers_all_alter_taskusers_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskusers',
            options={'ordering': ('all', '-natija')},
        ),
    ]
