# Generated by Django 4.2.9 on 2024-06-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_taskusers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskusers',
            options={'ordering': ('all', '-natija1', '-natija2')},
        ),
        migrations.RemoveField(
            model_name='taskusers',
            name='checking',
        ),
        migrations.RemoveField(
            model_name='taskusers',
            name='natija',
        ),
        migrations.AddField(
            model_name='taskusers',
            name='checking1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taskusers',
            name='checking2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taskusers',
            name='natija1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskusers',
            name='natija2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
