# Generated by Django 4.2.9 on 2024-06-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_taskusers_options_remove_taskusers_checking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskusers',
            old_name='checking1',
            new_name='checking',
        ),
    ]
